name: Node.js Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: bun ci
      - run: bun test

  publish-bun:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: bun ci

      - name: Publish package
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            bun publish --tag beta
          else
            bun publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.bun_TOKEN }}
